# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: mvnSettings
  displayName: 'Download Maven Settings'
  inputs:
    secureFile: 'settings.xml'
- script: |
    echo Installing $(mvnSettings.secureFilePath) to ${HOME}/.m2/settings.xml ...
    sudo chown root:root $(mvnSettings.secureFilePath)
    sudo chmod a+r $(mvnSettings.secureFilePath)
    sudo mkdir -p -m=777 ${HOME}/.m2
    sudo cp -f $(mvnSettings.secureFilePath) ${HOME}/.m2/settings.xml
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'deploy'
    options: '--non-recursive'